### PR TITLE
Added support for flashvars and a load complete callback

### PR DESCRIPTION
**Pull request by mdoolen**
Hi @jeef3 , I added two additional directive attributes:  swf-vars and swf-load.  swf-vars support the specification of flashvars on the swf object.  Use swf-load to register a callback on swf load complete.

The README file was updated to reflect these modifications.

### CODE REVIEW

**Comment by jeef3** [comment]
Hi @mdoolen, thanks for the PR! Nice additions too.

Could I possibly please ask you to fix the indentation and some of the spacing (e.g.: `if(thing){` should be `if (thing) {`. I know I don't exactly have a code guideline, or even an `editorconfig`, but it would be greatly appreciated.

**Comment by mdoolen** [comment]
@jeef3 , please let me know if the last commit satisfies your request.  Thanks!

**Comment by jeef3** [comment]
@mdoolen Thanks! Almost. Try to make it so that the [Files Changed](https://github.com/jeef3/angular-swfobject/pull/1/files) tab only shows the changes you've made. It looks like the whole file is still indented two spaces too far. You should be able to check this locally with (on your branch) `git diff master` for example.

Thanks again.

**Comment by mdoolen** [comment]
@jeef3 , the file _should_ have desired indent spacing now. Thanks

**Comment by jeef3** [comment]
@mdoolen Awesome, thanks for that. Makes it much easier to see the work you've done :smile:

**Pull request merged**
